### PR TITLE
Size, government, police

### PR DESCRIPTION
**Pull request by inalienable-wright**

### CODE REVIEW

**Comment by travis-adams** [comment]
why are there empty cases in Size and PolicePresence?

**Comment by inalienable-wright** [comment]
using fallthrough cases for weighted randomness: empty cases above fall through until they hit a return so it gives a bigger target while still letting me use a case statement and not and if-else with ranges

**Comment by travis-adams** [comment]
oh cool! sounds good

also unrelated: the random generator bound in Resource is 20, is that also fallthrough? So that most of the planets have no special resources?

**Comment by inalienable-wright** [comment]
nope, the 20 means the default NO_SPECIAL_RESOURCES is weighted 8x the other choices

**Comment by travis-adams** [comment]
alright looks good then fam

**Comment by inalienable-wright** [comment]
then lemme merge this boi

**Pull request merged**
